name: multipass-gui
version: git
version-script: |
  echo $(date --utc +%Y%m%d).$(git rev-parse HEAD | cut -c -7)
summary: Multipass
description: |
  Multipass allows you to to quickly launch Ubuntu virtual machines.

grade: stable
confinement: classic

apps:
  multipass-gui:
    command: usr/bin/multipass-gui
    desktop: usr/share/applications/multipass-gui.desktop

parts:
  multipass-gui:
    build-attributes: ['no-system-libraries']
    after: [desktop-gtk3]
    plugin: meson
    meson-parameters: [--prefix=/usr]
    source: .
    override-pull: |
      snapcraftctl pull
      version=$(date --utc +%Y%m%d).$(git rev-parse HEAD | cut -c -7)
      snapcraftctl set-version $version
    build-packages:
      - libgtk-3-dev
      - libvte-2.91-dev
    stage-packages:
      - libvte-2.91-0
