name: multipass-gui
adopt-info: multipass-gui
summary: Multipass
description: |
  Multipass allows you to to quickly launch Ubuntu virtual machines.

base: core18
grade: stable
confinement: classic

apps:
  multipass-gui:
    command: usr/bin/multipass-gui
    desktop: usr/share/applications/multipass-gui.desktop

parts:
  multipass-gui:
    after: [desktop-gtk3]
    plugin: meson
    meson-parameters: [--prefix=/usr]
    source: .
    override-pull: |
      snapcraftctl pull
      version=$(date --utc +%Y%m%d).$(git rev-parse HEAD | cut -c -7)
      snapcraftctl set-version $version
    build-packages:
      - libgtk-3-dev
      - libvte-2.91-dev
      - libxml2-utils
    stage-packages:
      - libvte-2.91-0
